name: BraVL
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - matplotlib=3.4.2
  - seaborn=0.11.2
  - numpy=1.19.1
  - python=3.7.0
  - pytorch=1.9.0
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - tensorboardx=2.4
  - torchvision=0.10.0
  - transformers=4.9.2
  - timm=0.4.12
